name: Build wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macOS-latest]

    steps:
      - uses: actions/checkout@v3
      - name: checkout submodules
        run: git submodule update --init --recursive

      # Used to host cibuildwheel
      - uses: actions/setup-python@v3

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.17.0 build wheel setuptools

      - name: Build sdist
        run: python -m build --no-isolation --sdist --outdir wheelhouse
        if: runner.os == 'Windows'

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        # to supply options, put them in 'env', like:
        env:
          CIBW_ARCHS: auto64
          CIBW_ARCHS_MACOS: universal2
          CIBW_ENVIRONMENT_MACOS: MACOSX_DEPLOYMENT_TARGET=10.15
          CIBW_MANYLINUX_X86_64_IMAGE: quay.io/pypa/manylinux_2_28_x86_64:latest 
          CIBW_BEFORE_ALL_LINUX: yum install -y clang || apt-get install clang || apk add clang
          CIBW_ENVIRONMENT_LINUX: CXX=clang++
          CIBW_ENVIRONMENT_PASS_LINUX: CXX
          # CIBW_SKIP: "*musl*"

      - uses: actions/upload-artifact@v3
        with:
          path: |
            ./wheelhouse/*.whl
            ./wheelhouse/*.tar.gz
